#! /bin/bash

# Build the site
echo "BUILDING THE SITE in '../site.programming.onepercent.xyz'"
echo "========================================================="
jekyll build -d ../site.programming.onepercent.xyz

# Go to the generated folder
cd ../site.programming.onepercent.xyz
rm -rf git_hooks

# Add a Git remote if it is not there
echo "TRYING TO PUSH SITE TO SITE REPO"
echo "========================================================="
date_now=$(date "+%Y-%m-%d_%H-%M-%S")
git init
git add . 
git commit "Update - $date_now"
git remote add origin git@github.com:vaibhav-kaushal/site.programming.onepercent.xyz.git
git push -u origin master

echo "PUSHED! Site should be updated in a few seconds"
echo "========================================================="