#! /bin/bash

# Echo messages to console
echo -e "\033[0;34m BUILDING THE SITE in '../site.programming.onepercent.xyz'"
echo -e "\033[0;34m ========================================================="
echo -e "\033[0;30m "

# Build the site
bundle exec jekyll build -d ../site.programming.onepercent.xyz

# Go to the generated folder
cd ../site.programming.onepercent.xyz
rm -rf git_hooks

echo "programming.onepercent.xyz" > CNAME

# Add a Git remote if it is not there
echo -e "\033[0;34m TRYING TO PUSH SITE TO SITE REPO"
echo -e "\033[0;34m ========================================================="
date_now=$(date "+%Y-%m-%d_%H-%M-%S")

# Print whether git repo exists or not
# and initialize one if it does not exist
if [ -d .git ]; then
  echo -e "\033[0;33m Git repo already exists";
else
  echo -e "\033[0;33m Git repo does not exist. Trying to initialize one"
  git init
fi;

echo -e "\033[0;30m "

# Add all files and commit
git add . 
git commit -m "Update - $date_now"

# Does a remote named 'origin' exist?
origin_count=$(git remote | grep -i "^origin$" | wc -l | xargs)

if [ 1 -eq $origin_count ]; then
	echo -e "\033[0;34m Origin remote already exists."
else
	echo -e "\033[0;31m Origin remote does not exist. Trying to create remote."
	git remote add origin git@github.com:vaibhav-kaushal/site.programming.onepercent.xyz.git
fi

echo -e "\033[0;30m "

# Attempting to push
git push -u origin master

echo -e "\033[0;34m PUSHED! Site should be updated in a few seconds"
echo -e "\033[0;34m ========================================================="
echo -e "\033[0;30m "